In [1]:
import numpy as np

In [2]:
np.random.randint(20)

11

In [3]:
np.random.randint(30, size = 10)

array([24, 18,  6,  2, 13,  4, 14,  1,  6, 29])

In [7]:
np.random.randint(200,size = 5)

array([179,  72,  32, 197, 122])

In [10]:
np.random.normal(40,size = 10)

array([39.64711339, 41.16156299, 38.11827194, 41.09193595, 38.55836919,
       38.48226683, 41.69903609, 40.89178471, 39.78999411, 39.67499312])

In [13]:
np.random.gamma(3,size = 5)

array([1.80587429, 0.8641013 , 1.67758664, 4.16832314, 4.11499026])

In [20]:
np.random.seed(45)

# Reshape

In [22]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
a.reshape(3,4 ,order='c')

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
a.reshape(3,4 ,order='f')

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [30]:
a.reshape(6,2 ,order='c')

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [31]:
a.reshape(6,2 ,order='f')

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [36]:
b = a.reshape(2,2,3 ,order='c')
b.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
c = a.reshape(2,3,2 ,order='f')
c.flatten()

array([ 1,  7,  3,  9,  5, 11,  2,  8,  4, 10,  6, 12])

# Concatenation

In [38]:
x = np.arange(1,5)
x
y= np.arange(6,10)
y

array([6, 7, 8, 9])

In [39]:
x

array([1, 2, 3, 4])

In [40]:
np.concatenate((x,y) , axis = 0)

array([1, 2, 3, 4, 6, 7, 8, 9])

In [42]:
np.hstack((x,y))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [43]:
np.vstack((x,y))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

# Splitting

In [48]:
z = np.arange(1,16)

In [49]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [50]:
np.split(z,[3,6,9,12])

[array([1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8, 9]),
 array([10, 11, 12]),
 array([13, 14, 15])]

# Repeat 

In [55]:
aa = np.array([1,2,3,4])
aa

array([1, 2, 3, 4])

In [58]:
np.repeat(aa,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [60]:
np.tile(aa,55)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2,
       3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4,
       1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2,
       3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4,
       1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2,
       3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4,
       1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2,
       3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4,
       1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2,
       3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])